version: 'latest'
services:
  database:
    image: mysql:latest
    restart: always
    container_name: database
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      # Opens port 3306 on the container
      - '${DB_PORT}'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - gateway-microservice_localnet
  plants_app:
    container_name: plants_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    volumes:
      - ./src:/usr/src/app/plants/src
    depends_on:
      database:
        condition: service_healthy
    networks:
      - gateway-microservice_localnet
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
    depends_on:
      database:
        condition: service_healthy
    networks:
      - gateway-microservice_localnet

networks:
  gateway-microservice_localnet:
    external: true