services:
  plants-microservice:
    build:
      context: .
      dockerfile: Dockerfile.prod # Use Dockerfile.prod for production
    environment:
      NODE_ENV: production
  database:
    image: yobasystems/alpine-mariadb # ARMv7 MySQL Docker image
  phpmyadmin: !reset